MisPerris/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.formulario.views import formulario_view
from apps.principal.views import IndexView,LogOut
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^formulario/', formulario_view, name='contacto'),
    url(r'^rescate/', include(('apps.rescate.urls','rescate'),namespace='rescate')),
    url(r'^adopcion/', include(('apps.adopcion.urls','adopcion'),namespace='adopcion')),
    url('', include('social.apps.django_app.urls', namespace='social')), 
    url(r'^salir/$', LogOut),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/adopcion/urls.py
from .views import lista_adopcion,asignar_adopcion,adopta_perro
from django.conf.urls import url,include

urlpatterns = [
    url(r'^ver$', lista_adopcion, name='ver'),
    url(r'^asignar$', asignar_adopcion, name='asignar'),
    url(r'^adopta/(?P<id_adopcion>\d+)/$', adopta_perro, name='adopta'),
]

apps/adopcion/models.py
from django.db import models
from apps.formulario.models import Contacto
from apps.rescate.models import perrito,Estado
# Create your models here.
default_D = 1
class Adopcion(models.Model):
    rut = models.ForeignKey(Contacto, on_delete=models.CASCADE)
    id_perro = models.OneToOneField(perrito,on_delete=models.CASCADE,unique = True)
    id_estado = models.ForeignKey(Estado,on_delete=models.CASCADE,default=default_D)

apps/adopcion/forms.py
from django import forms
from .models import Adopcion
class formAdopcion(forms.ModelForm):
    class Meta:
        model = Adopcion
        fields = [
            'rut',
            'id_perro',
            'id_estado',
        ]
        widgets = {
            'rut': forms.Select(attrs={'class':'form-control col-10'}),
            'id_perro': forms.Select(attrs={'class':'form-control col-10'}),
            'id_estado': forms.Select(attrs={'class':'form-control col-10'}),
        }
        labels = {
            'rut': 'Rut del dueño',
            'id_perro': 'ID de la mascota',
        }
class formAdopcion2(forms.ModelForm):
    class Meta:
        model = Adopcion
        fields = [
            'rut',
            'id_perro',
            'id_estado',
        ]
        widgets = {
            'rut': forms.TextInput(attrs={'class':'form-control col-10','readonly':'True'}),
            'id_perro': forms.TextInput(attrs={'class':'form-control col-10','readonly':'True'}),
            'id_estado': forms.Select(attrs={'class':'form-control col-10'}),
        }
        labels = {
            'rut': 'Rut del dueño',
            'id_perro': 'ID de la mascota',
        }

apps/adopcion/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import Adopcion
from .forms import formAdopcion,formAdopcion2
from apps.rescate.models import Estado
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def lista_adopcion(request):
    adopta = Adopcion.objects.all()
    return render(request, "adopcion/ver.html",{'adopta':adopta})
@login_required
def asignar_adopcion(request):
    form = formAdopcion(request.POST)
    if form.is_valid():
      form.save()
      return redirect('adopcion:ver')
    context =  {
        'form': form,
    }
    return render(request,'adopcion/nueva.html',context)
@login_required
def adopta_perro(request,id_adopcion):  
    adop = Adopcion.objects.get(id = id_adopcion)
    if request.method == 'GET':
        form = formAdopcion2(instance=adop)
    else:
        form = formAdopcion2(request.POST, instance=adop)
        if form.is_valid():
            form.save()
        return redirect('adopcion:ver')
    context =  {
        'form': form,
        'adop':adop,
    }
    return render(request,'adopcion/adopta.html',context)

templates/adopcion/adopta.html
{% extends 'base/base.html' %}
{% block title %}Adoptar mascota{% endblock %}
{% block content %}
<form method="POST" enctype='multipart/form-data' class="Articulo2-2 col-12">
   
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-12">
                <h2>Deseea adoptar a esta mascota  ?</h2>
            </div>
            <img class="img-fluid p-2 "  style="border-style: solid;border-width: 2"  src="{{adop.id_perro.imagen.url}}" alt="">
           <div class="form-group">
                {% csrf_token %}
                {{form}}
           </div>
           <input class="btn btn-primary btn-block btn-success" value="Si" type="submit">
        </div>
    </div>
</form>
{% endblock %}

templates/adopcion/nueva.html
{% extends 'base/base.html' %}
{% block title %}Adopcion asignar{% endblock %}
{% block content %}
    <div class="container">
        <div class="jumbotron mt-5 ">
            <div class="row justify-content-center mb-3">
                    <div class="co1-12 ">
                        <h2>Asigna a un dueño para adoptar a este perrito!</h2>
                    </div>
                    <form method="POST" enctype='multipart/form-data' class="Articulo2-2 col-12">
                        {% csrf_token %}
                        <div class="form-group row justify-content-center m-3 ">
                            <div class="col-6 mt-2">
                                {{form.as_p}}
                            </div>
                           
                        </div>
                        <div class="form-group row justify-content-center">
                                <div class="col-12 col-sm-9 col-md-4">
                                  <input class="btn btn-primary btn-block btn-success" value="Enviar" type="submit">
                              </div>
                            
                          </div>
                    </form>
                </div>
        </div>
          
    </div>


{% endblock %}

templates/adopcion/ver.html
{% extends 'base/base.html' %}
{% block title %}Rescate{% endblock %}
{% block content %}
    
    {% for obj in adopta  %}

       <div class="row  justify-content-center mt-5 mb-2 p-2 border border-success">
           <div class="col-12 text-center m-2">
                <h2>Adopciones</h2>
           </div>
           <div class="col-lg-4 col-md-4  justify-content-center">
            <img class="img-fluid p-2 "  style="border-style: solid;border-width: 2"  src="{{obj.id_perro.imagen.url}}" alt="">
           </div>
           <div class="col-12 justify-content-center text-center m-2">
                <h2>--Datos--</h2>
                <p>Nombre de la mascota: {{obj.id_perro.nombrePerro}}</p>
                <p>Nombre del dueño: {{obj.rut.nombres| add:obj.rut.apPaterno | add:obj.rut.apMaterno}}</p>
                <p>Rut dueño: {{obj.rut.nombres}}-{{obj.rut.dvRut}}</p>
                {% if obj.id_estado.estado == "Disponible" %}
                <form method="POST" class="Articulo2-2 col-12">
                        {% csrf_token %}
                        <a name="" id="" class="btn btn-success m-2 p-3 fas fa-paw " href="{% url 'adopcion:adopta' obj.id %}" role="button">Dar en adopción</a>
                    </form>   
                {% elif obj.id_estado.estado == "Adoptado" %}
                <div class="alert alert-danger fas fa-frown" role="alert">
                        <h4 class="alert-heading"></h4>
                        <p>Mascota ya adoptada!</p>
                        <p class="mb-0"></p>
                      </div>
                {% else %}
                    jojo
                {% endif %}          
           </div>

       </div>

    {% endfor %}
        
{% endblock %}