MisPerris/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.formulario.views import formulario_view
from apps.principal.views import IndexView,LogOut
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^formulario/', formulario_view, name='contacto'),
    url(r'^rescate/', include(('apps.rescate.urls','rescate'),namespace='rescate')),
    url(r'^adopcion/', include(('apps.adopcion.urls','adopcion'),namespace='adopcion')),
    url('', include('social.apps.django_app.urls', namespace='social')), 
    url(r'^salir/$', LogOut),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/rescate/urls.py
from apps.rescate.views import lista_rescate,crea_rescate,edita_rescate,elimina_rescate
from django.conf.urls import url,include

urlpatterns = [
    url(r'^ver$', lista_rescate, name='ver'),
    url(r'^crea$', crea_rescate, name='crea'),
    url(r'^modifica/(?P<id_perrito>\d+)/$', edita_rescate, name='edita'),
    url(r'^delete/(?P<id_perrito>\d+)/$', elimina_rescate, name='r_delete'),
]

apps/rescate/models.py
from django.db import models
from apps.formulario.models import Contacto

# Create your models here.
class Estado(models.Model):
    estado = models.CharField(max_length=50,blank=True, null=True)
    def __str__(self):
        return self.estado

default_D = 1       
class perrito(models.Model):
    nombrePerro = models.CharField(max_length=50)
    razaP = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    imagen =  models.FileField(max_length=None, upload_to='media')
    estado = models.OneToOneField(Estado, on_delete=models.CASCADE,null = True,default=default_D)

    def __str__(self):
        return self.nombrePerro + ' ' + self.razaP + ' ' + self.descripcion 

apps/rescate/forms.py
from django import forms

from apps.rescate.models import perrito

class formServicio(forms.ModelForm):
    class Meta:
        model = perrito
        fields = [
            'nombrePerro',
            'razaP',
            'descripcion',
            'imagen',
        ]
        widgets = {
            'nombrePerro': forms.TextInput(attrs={'class':'form-control col-10'}),
            'razaP': forms.TextInput(attrs={'class':'form-control col-10'}),
            'descripcion': forms.Textarea(attrs={'class':'form-control col-10'}),
        }
        labels = {
            'nombrePerro': 'Nombres',
            'razaP': 'Raza del perro',
            'descripcion': 'Descripcion',
            'imagen': 'Imagen',
        }


        

apps/rescate/views.py
from django.shortcuts import render,redirect
from .models import perrito
from apps.rescate.forms import formServicio
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def lista_rescate(request):
    rescata = perrito.objects.all()
    return render(request, "rescate/rescate.html",{'rescata':rescata})
@login_required
def crea_rescate(request):
    form = formServicio(request.POST, request.FILES or None)
    if form.is_valid():
      form.save()
      return redirect('index')
    else:
        form = formServicio()
    context =  {
        'form': form,
    }
    return render(request,'rescate/nuevo.html',context)
@login_required
def edita_rescate(request,id_perrito):
    perro = perrito.objects.get(id = id_perrito)
    if request.method == 'GET':
        form = formServicio(instance=perro)
    else:
        form = formServicio(request.POST, request.FILES or None, instance=perro)
        if form.is_valid():
            form.save()
        return redirect('rescate:ver')
    return render(request,'rescate/edita.html',{'form':form})
@login_required
def elimina_rescate(request,id_perrito):
    perro = perrito.objects.get(id = id_perrito)
    if request.method == 'POST':
        perro.delete()
        return redirect('rescate:ver')
    return render(request,'rescate/elimina.html',{'perro':perro})
        

templates/rescate/edita.html
{% extends 'base/base.html' %}
{% block title %}Rescate edita{% endblock %}
{% block content %}
    <div class="container">
        <div class="jumbotron mt-5 ">
            <div class="row justify-content-center mb-3">
                    <div class="co1-12 ">
                        <h2>Rescata a un perrito!</h2>
                        <p>Ingresa la info de un nuevo amigo</p>
                    </div>
                    <form method="POST" enctype='multipart/form-data' class="Articulo2-2 col-12">
                        {% csrf_token %}
                        <div class="form-group row justify-content-center m-3 ">
                            <div class="col-6 mt-2">
                                {{form.as_p}}
                            </div>
                           
                        </div>
                        <div class="form-group row justify-content-center">
                                <div class="col-12 col-sm-9 col-md-4">
                                  <input class="btn btn-primary btn-block btn-success" value="Enviar" type="submit">
                              </div>
                            
                          </div>
                    </form>
                </div>
        </div>
          
    </div>
    

{% endblock %}

templates/rescate/elimina.html
{% extends 'base/base.html' %}
{% block title %}Rescate elimina{% endblock %}
{% block content %}
<form method="POST" class="Articulo2-2 col-12">
    {% csrf_token %}
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-12">
                <h2>Deseea eliminar a este perrito de el registro ? </h2><p>{{perro.nombrePerro}}</p>
            </div>
            <button class="btn-success m-2 p-3" type="submit">SI</button>
            <a name="" id="" class="btn btn-danger m-2 p-3" href="{% url 'rescate:ver' %}" role="button">NO</a>
        </div>
    </div>
</form>
{% endblock %}

templates/rescate/nuevo.html
{% extends 'base/base.html' %}
{% block title %}Rescate añade{% endblock %}
{% block content %}
    <div class="container">
        <div class="jumbotron ">
            <div class="row justify-content-center mb-3">
                    <div class="co1-12 ">
                        <h2>Rescata a un perrito!</h2>
                        <p>Ingresa la info de un nuevo amigo</p>
                    </div>
                    <form method="POST" enctype='multipart/form-data' class="Articulo2-2 col-12">
                        {% csrf_token %}
                        <div class="form-group row justify-content-center m-3 ">
                            <div class="col-6 mt-2">
                                {{form.as_p}}
                            </div>
                           
                        </div>
                        <div class="form-group row justify-content-center">
                                <div class="col-12 col-sm-9 col-md-4">
                                  <input class="btn btn-primary btn-block btn-success" value="Enviar" type="submit">
                              </div>
                            
                          </div>
                    </form>
                </div>
        </div>
          
    </div>
    

{% endblock %}

templates/rescate/rescate.html
{% extends 'base/base.html' %}
{% block title %}Rescate{% endblock %}
{% block content %}
    
    {% for resc in rescata  %}
       <div class="row  text-md-left text-center mt-5 mb-2 pt-3 border border-success">
            
           <div class="col-lg-4 col-md-4 offset-lg-1  ">
            {% if resc.imagen %}
            <img class="img-fluid mb-2" src="{{resc.imagen.url}}" alt="">
           {% endif %}
           </div>
           <div class="col-lg-7 col-md-8 ">
                <h2 class="section-heading title">{{resc.nombrePerro}}</h2>
                <p>Raza del perrito: {{resc.razaP}}</p>
                <p>Descripcion: {{resc.descripcion}}</p>
                <p>Estado del perrito: {{resc.estado}}</p>
                <a name="boton"  id="" class="btn btn-danger" href="{% url 'rescate:r_delete' resc.id %}" role="button">Borrar</a>
                <a name="" id="" class="btn btn-primary" href="{% url 'rescate:edita' resc.id %}" role="button">Editar</a>
           </div> 
       </div>

    {% endfor %}
        
{% endblock %}